name: Test

on:
  push:
    branches: "*"
  pull_request:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Install latest LLVM (clang)
        shell: powershell
        run: |
          winget install LLVM.LLVM --accept-source-agreements --silent
      - name: Clang version
        run: |
          clang --version
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Build
        run: |
          cargo build
        env:
          RUST_BACKTRACE: full
