name: Test

on:
  push:
    branches: "*"
  pull_request:

jobs:
  test2:
    name: Test ${{matrix.name || format('Rust {0}', matrix.rust)}}
    runs-on: ${{matrix.os || 'ubuntu'}}-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - rust: stable
          # Windows GNU disabled due to https://github.com/google/autocxx/issues/1134
          # - name: Windows (gnu)
          #    rust: nightly-x86_64-pc-windows-gnu
          #    os: windows
          - name: Windows (msvc)
            rust: nightly-x86_64-pc-windows-msvc
            os: windows
            flags: /EHsc
    env:
      CXXFLAGS: ${{matrix.flags}}
      RUSTFLAGS: --cfg deny_warnings -Dwarnings

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt
      # The `{ sharedKey: ... }` allows different actions to share the cache.
      - uses: Swatinem/rust-cache@v1
        with: { sharedKey: fullBuild }
      # For operating systems that have it packaged, install creduce
      - name: Install creduce (Linux)
        if: matrix.os == ''
        run: sudo apt-get install creduce
      - name: Install creduce (MacOS)
        if: matrix.os == 'macOS'
        run: brew install creduce
      - name: Set LIBCLANG_PATH (Windows)
        # Windows github action doesn't set the path for clang, so set it
        # See https://github.com/rust-lang/rust-bindgen/issues/1797
        if: matrix.os == 'windows'
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - name: Exclude failing targets and tests
        # no creduce on Windows, so exclude tests needing creduce there
        run: |
          echo RUSTFLAGS=$RUSTFLAGS >> $GITHUB_ENV
          echo ::set-output name=exclude::${{runner.os == 'Windows' && '--exclude autocxx-reduce --exclude autocxx-gen' || ''}}
        env:
          # non-linux failures https://github.com/google/autocxx/issues/819
          # beta failing tests https://github.com/google/autocxx/issues/818
          RUSTFLAGS: ${{matrix.name == 'Windows (msvc)' && '--cfg skip_windows_msvc_failing_tests' || ''}} ${{matrix.name == 'Windows (gnu)' && '--cfg skip_windows_gnu_failing_tests' || ''}}
        id: testsuite
        shell: bash
      - run: cargo build
